# https://github.com/coinbase/salus/blob/master/docs/configuration.md

# Used in the report to identify the project being scanned.
project_name: terraform-provider-doppler

# Defines where to send Salus reports and in what format.
reports:
  - uri: file://salus-report.txt
    format: txt

# All scanners to execute, or the String value "all"/"none"
active_scanners:
  - Gosec
  - PatternSearch
  - RepoNotEmpty
  - GoOSV
  - GoVersionScanner
  - GoPackageScanner
  - ReportGoDep
  - Trufflehog

# All scanners that will exit non-zero if they fail, or the String value "all"/"none"
enforced_scanners: "all"

scanner_configs:
  GoVersionScanner:
    error:
      min_version: "1.24.0" # GO_VERSION_DEF

  GoOSV:
    exceptions:
      - advisory_id: GHSA-29qp-crvh-w22m
        changed_by: nmanoogian
        notes: This advisory has been withdrawn
        expiration: "2026-01-01"
      - advisory_id: GO-2025-3408
        changed_by: nmanoogian
        notes: This advisory has been withdrawn
        expiration: "2026-01-01"
